### ISSUE TITLE
Deactivate team on discord permission errors

### ISSUE THREAD

**Issue by dblock** [dblock/discord-strava#6]
```
[discord-strava] [2024-01-07 12:15:14] I, [2024-01-07T12:15:14.485276 #1]  INFO -- : Bragging about user_id=..., user_name=..., id=..., name=Walk around the park, date=2024-01-01T14:06:02+00:00, distance=1.61mi, moving time=32m56s, pace=20m25s/mi, proxy=.
[discord-strava] [2024-01-07 12:15:14] I, [2024-01-07T12:15:14.486273 #1]  INFO -- : Posting '{:embeds=>[{:title=>"Walk around the park", :url=>"https://www.strava.com/activities/...", :description=>"<@...> on Monday, January 01, 2024 at 02:06 PM", :fields=>[{:inline=>true, :name=>"Type", :value=>"Walk \u{1F6B6}"}, {:inline=>true, :name=>"Distance", :value=>"1.61mi"}, {:inline=>true, :name=>"Time", :value=>"32m56s"}, {:inline=>true, :name=>"Pace", :value=>"20m25s/mi"}, {:inline=>true, :name=>"Speed", :value=>"2.9mph"}, {:inline=>true, :name=>"Elevation", :value=>"92.8ft"}], :timestamp=>"2024-01-07T12:15:14Z", :author=>{:name=>"Cody Cody", :url=>"https://www.strava.com/athletes/..."}}]}' for user_id=..., user_name=... on ....
[discord-strava] [2024-01-07 12:15:14] W, [2024-01-07T12:15:14.592551 #1]  WARN -- : Bragging to user_id=..., user_name=... failed, the server responded with status 403.
[discord-strava] [2024-01-07 12:15:14] W, [2024-01-07T12:15:14.593086 #1]  WARN -- : Error in team guild_id=..., guild_name=..., user_id=..., user_name=..., the server responded with status 403, {"message"=>"Missing Access", "code"=>50001}, /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:20:in `on_complete'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/lib/discord/server.rb:26:in `http_method'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/lib/discord/server.rb:8:in `post'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/lib/discord/messages.rb:15:in `send_message'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/user.rb:44:in `inform!'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/association/proxy.rb:137:in `method_missing'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/user_activity.rb:35:in `brag!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/user.rb:153:in `brag_new_activities!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/user.rb:141:in `brag!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/brag.rb:26:in `block in sync_and_brag!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/brag.rb:3:in `with_strava_error_handler'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/models/brag.rb:24:in `sync_and_brag!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:173:in `block (2 levels) in users_brag_and_rebrag!'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:710:in `yield_document'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:137:in `block in each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/collection/view/iterable.rb:51:in `block in each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/cursor.rb:163:in `block in each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/cursor.rb:161:in `loop'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/cursor.rb:161:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/collection/view/iterable.rb:50:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/query_cache.rb:228:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:136:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/ruby/vendor/ruby-2.7.7/lib/ruby/2.7.0/forwardable.rb:235:in `each'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:172:in `block in users_brag_and_rebrag!'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:710:in `yield_document'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:137:in `block in each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/collection/view/iterable.rb:51:in `block in each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/cursor.rb:163:in `block in each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/cursor.rb:161:in `loop'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/cursor.rb:161:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongo-2.12.1/lib/mongo/collection/view/iterable.rb:50:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/query_cache.rb:228:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:136:in `each'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/ruby/vendor/ruby-2.7.7/lib/ruby/2.7.0/forwardable.rb:235:in `each'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:165:in `users_brag_and_rebrag!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:62:in `block (2 levels) in after_start!'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:92:in `block (2 levels) in continuously'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:91:in `loop'
[discord-strava] [2024-01-07 12:15:14] /workspace/discord-strava/app.rb:91:in `block in continuously'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/async-1.31.0/lib/async/task.rb:261:in `block in make_fiber'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-9.4.2/lib/new_relic/agent/tracer.rb:435:in `block (2 levels) in thread_block_with_current_transaction'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-9.4.2/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
[discord-strava] [2024-01-07 12:15:14] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-9.4.2/lib/new_relic/agent/tracer.rb:434:in `block in thread_block_with_current_transaction'.

```

**Comment by dblock** [comment]
The problem is that a strava error causes a `dm_connect!` which itself fails.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/discord-strava/commit/5d95e1cebddd646d01f621db3be645e0d9276bb4.
